import '../global.css';
import './style.css';
import './youtube-options';

/* 

1. INIT TEMPLATE WITH DEFAULT CONFIG
2. FETCH ALL CONFIGS. GLOBAL, YOUTUBE, TWITTER, FACEBOOK...
3. PASS CONFIG TO TEMPLATE
4. ON INPUT CHANGE, CHANGE CORRESPONDING CONFIG STORAGE.

*/
